### ISSUE TITLE
Derived attributes incorrectly implemented

### ISSUE THREAD

**Issue by kbaltrinic** [chef-cookbooks/git#79]
I just learned how to do this correctly myself so don't take this harshly, but the implementation of the derived ['git']['url'] attribute on [Line 6](['sonarqube']['config']['dir']) of attrbutes/default.rb is problematic.  The following article details why and how to fix: https://coderanger.net/derived-attributes/

Regards

**Comment by vinyar** [comment]
@kbaltrinic thanks. Neat article!! It was written before chef client 12 was released, I wonder if it's still applicable.

**Comment by kbaltrinic** [comment]
I was discussing the problem with some of the Chef team at a local meetup and they were the ones to point me to it.  It might be going a bit far to call it the "official" approach to the problem but I am pretty sure its still current an valid.

**Comment by lamont-granquist** [comment]
We fundamentally cannot fix it without inverting the order of attributes files parsing and breaking other use cases (which we won't ever do).

Noah's suggestion looks good, the delayed interpolation operator looks like it's supported back to ruby 1.9.3 at least.   Its also possible to just use plain old ruby variables at compile-time in order to get the same result:

https://github.com/chef-cookbooks/erlang/pull/35

Also, this cookbook exposes resources, and the recipes are trivial.  Users are encouraged to not use the recipes in this cookbook at all, and write their own recipes and design their own systems of the attributes they need, if they actually have a requirement for them.

**Comment by scalp42** [comment]
Any chance anybody could take a look at https://github.com/chef-cookbooks/git/pull/89 ?

**Comment by iennae** [comment]
Thanks @scalp42 for your contributions. Released cookbook 4.3.7 should resolve this problem. Updates to documentation forthcoming.
